// api/civics.js
// Official USCIS civics test data. The questions/answers are U.S. government works (public domain).
//
// IMPORTANT — KEEP THIS UPDATED:
// The values in CURRENT_OFFICIALS change with elections and appointments.
// When a new President, Vice President, Speaker, or Chief Justice takes office,
// update the strings below. Last verified: June 2026.

const CURRENT_OFFICIALS = {
  president: 'Donald Trump',
  vicePresident: 'JD Vance',
  presidentParty: 'Republican (Party)',
  speaker: 'Mike Johnson',
  chiefJustice: 'John Roberts'
};

// For questions whose answer depends on the applicant's state/district.
const STATE = 'Answer varies by the applicant\'s state — first ask which U.S. state they live in, then accept the correct current answer for that state. (Washington, D.C. residents have no Senators/Representative/Governor; D.C. is not a state.)';

// 2008 test: 100 questions. The officer asks up to 10; the applicant must answer 6 correctly to pass.
const CIVICS_2008 = [
  { n: 1,  q: 'What is the supreme law of the land?', a: 'the Constitution' },
  { n: 2,  q: 'What does the Constitution do?', a: 'sets up the government; defines the government; protects basic rights of Americans' },
  { n: 3,  q: 'The idea of self-government is in the first three words of the Constitution. What are these words?', a: 'We the People' },
  { n: 4,  q: 'What is an amendment?', a: 'a change (to the Constitution); an addition (to the Constitution)' },
  { n: 5,  q: 'What do we call the first ten amendments to the Constitution?', a: 'the Bill of Rights' },
  { n: 6,  q: 'What is one right or freedom from the First Amendment?', a: 'speech; religion; assembly; press; petition the government' },
  { n: 7,  q: 'How many amendments does the Constitution have?', a: 'twenty-seven (27)' },
  { n: 8,  q: 'What did the Declaration of Independence do?', a: 'announced/declared our independence from Great Britain; said that the United States is free from Great Britain' },
  { n: 9,  q: 'What are two rights in the Declaration of Independence?', a: 'life; liberty; pursuit of happiness' },
  { n: 10, q: 'What is freedom of religion?', a: 'You can practice any religion, or not practice a religion.' },
  { n: 11, q: 'What is the economic system in the United States?', a: 'capitalist economy; market economy' },
  { n: 12, q: 'What is the "rule of law"?', a: 'Everyone must follow the law; Leaders/Government must obey the law; No one is above the law.' },
  { n: 13, q: 'Name one branch or part of the government.', a: 'Congress (legislative); President (executive); the courts (judicial)' },
  { n: 14, q: 'What stops one branch of government from becoming too powerful?', a: 'checks and balances; separation of powers' },
  { n: 15, q: 'Who is in charge of the executive branch?', a: 'the President' },
  { n: 16, q: 'Who makes federal laws?', a: 'Congress; the Senate and House (of Representatives); the (U.S./national) legislature' },
  { n: 17, q: 'What are the two parts of the U.S. Congress?', a: 'the Senate and House (of Representatives)' },
  { n: 18, q: 'How many U.S. Senators are there?', a: 'one hundred (100)' },
  { n: 19, q: 'We elect a U.S. Senator for how many years?', a: 'six (6)' },
  { n: 20, q: "Who is one of your state's U.S. Senators now?", a: STATE },
  { n: 21, q: 'The House of Representatives has how many voting members?', a: 'four hundred thirty-five (435)' },
  { n: 22, q: 'We elect a U.S. Representative for how many years?', a: 'two (2)' },
  { n: 23, q: 'Name your U.S. Representative.', a: STATE },
  { n: 24, q: 'Who does a U.S. Senator represent?', a: 'all people of the state' },
  { n: 25, q: 'Why do some states have more Representatives than other states?', a: "(because of) the state's population; because some states have more people" },
  { n: 26, q: 'We elect a President for how many years?', a: 'four (4)' },
  { n: 27, q: 'In what month do we vote for President?', a: 'November' },
  { n: 28, q: 'What is the name of the President of the United States now?', a: '__PRESIDENT__' },
  { n: 29, q: 'What is the name of the Vice President of the United States now?', a: '__VICE_PRESIDENT__' },
  { n: 30, q: 'If the President can no longer serve, who becomes President?', a: 'the Vice President' },
  { n: 31, q: 'If both the President and the Vice President can no longer serve, who becomes President?', a: 'the Speaker of the House' },
  { n: 32, q: 'Who is the Commander in Chief of the military?', a: 'the President' },
  { n: 33, q: 'Who signs bills to become laws?', a: 'the President' },
  { n: 34, q: 'Who vetoes bills?', a: 'the President' },
  { n: 35, q: "What does the President's Cabinet do?", a: 'advises the President' },
  { n: 36, q: 'What are two Cabinet-level positions?', a: 'Secretary of State, Defense, Treasury, etc.; the Attorney General; the Vice President' },
  { n: 37, q: 'What does the judicial branch do?', a: 'reviews/explains laws; resolves disputes; decides if a law goes against the Constitution' },
  { n: 38, q: 'What is the highest court in the United States?', a: 'the Supreme Court' },
  { n: 39, q: 'How many justices are on the Supreme Court?', a: 'nine (9)' },
  { n: 40, q: 'Who is the Chief Justice of the United States now?', a: '__CHIEF_JUSTICE__' },
  { n: 41, q: 'Under our Constitution, some powers belong to the federal government. What is one power of the federal government?', a: 'to print money; to declare war; to create an army; to make treaties' },
  { n: 42, q: 'Under our Constitution, some powers belong to the states. What is one power of the states?', a: 'provide schooling/education; provide protection (police); provide safety (fire departments); give a driver\'s license; approve zoning and land use' },
  { n: 43, q: 'Who is the Governor of your state now?', a: STATE },
  { n: 44, q: 'What is the capital of your state?', a: STATE },
  { n: 45, q: 'What are the two major political parties in the United States?', a: 'Democratic and Republican' },
  { n: 46, q: 'What is the political party of the President now?', a: '__PRESIDENT_PARTY__' },
  { n: 47, q: 'What is the name of the Speaker of the House of Representatives now?', a: '__SPEAKER__' },
  { n: 48, q: 'There are four amendments to the Constitution about who can vote. Describe one of them.', a: 'Citizens eighteen (18) and older can vote; you don\'t have to pay a poll tax to vote; any citizen can vote (women and men); a male citizen of any race can vote' },
  { n: 49, q: 'What is one responsibility that is only for United States citizens?', a: 'serve on a jury; vote in a federal election' },
  { n: 50, q: 'Name one right only for United States citizens.', a: 'vote in a federal election; run for federal office' },
  { n: 51, q: 'What are two rights of everyone living in the United States?', a: 'freedom of expression/speech; freedom of assembly; freedom to petition the government; freedom of religion; the right to bear arms' },
  { n: 52, q: 'What do we show loyalty to when we say the Pledge of Allegiance?', a: 'the United States; the flag' },
  { n: 53, q: 'What is one promise you make when you become a United States citizen?', a: 'give up loyalty to other countries; defend the Constitution and laws of the U.S.; obey the laws of the U.S.; serve in the military or do important work for the nation if needed; be loyal to the U.S.' },
  { n: 54, q: 'How old do citizens have to be to vote for President?', a: 'eighteen (18) and older' },
  { n: 55, q: 'What are two ways that Americans can participate in their democracy?', a: 'vote; join a political party; help with a campaign; join a civic/community group; give an elected official your opinion; call Senators and Representatives; run for office; write to a newspaper' },
  { n: 56, q: 'When is the last day you can send in federal income tax forms?', a: 'April 15' },
  { n: 57, q: 'When must all men register for the Selective Service?', a: 'at age eighteen (18); between eighteen (18) and twenty-six (26)' },
  { n: 58, q: 'What is one reason colonists came to America?', a: 'freedom; political liberty; religious freedom; economic opportunity; to practice their religion; to escape persecution' },
  { n: 59, q: 'Who lived in America before the Europeans arrived?', a: 'American Indians; Native Americans' },
  { n: 60, q: 'What group of people was taken to America and sold as slaves?', a: 'Africans; people from Africa' },
  { n: 61, q: 'Why did the colonists fight the British?', a: 'because of high taxes (taxation without representation); because the British army stayed in their houses (boarding, quartering); because they didn\'t have self-government' },
  { n: 62, q: 'Who wrote the Declaration of Independence?', a: '(Thomas) Jefferson' },
  { n: 63, q: 'When was the Declaration of Independence adopted?', a: 'July 4, 1776' },
  { n: 64, q: 'There were 13 original states. Name three.', a: 'New Hampshire, Massachusetts, Rhode Island, Connecticut, New York, New Jersey, Pennsylvania, Delaware, Maryland, Virginia, North Carolina, South Carolina, Georgia' },
  { n: 65, q: 'What happened at the Constitutional Convention?', a: 'The Constitution was written; the Founding Fathers wrote the Constitution' },
  { n: 66, q: 'When was the Constitution written?', a: '1787' },
  { n: 67, q: 'The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.', a: '(James) Madison; (Alexander) Hamilton; (John) Jay; Publius' },
  { n: 68, q: 'What is one thing Benjamin Franklin is famous for?', a: 'U.S. diplomat; oldest member of the Constitutional Convention; first Postmaster General; writer of "Poor Richard\'s Almanac"; started the first free libraries' },
  { n: 69, q: 'Who is the "Father of Our Country"?', a: '(George) Washington' },
  { n: 70, q: 'Who was the first President?', a: '(George) Washington' },
  { n: 71, q: 'What territory did the United States buy from France in 1803?', a: 'the Louisiana Territory; Louisiana' },
  { n: 72, q: 'Name one war fought by the United States in the 1800s.', a: 'War of 1812; Mexican-American War; Civil War; Spanish-American War' },
  { n: 73, q: 'Name the U.S. war between the North and the South.', a: 'the Civil War; the War between the States' },
  { n: 74, q: 'Name one problem that led to the Civil War.', a: 'slavery; economic reasons; states\' rights' },
  { n: 75, q: 'What was one important thing that Abraham Lincoln did?', a: 'freed the slaves (Emancipation Proclamation); saved/preserved the Union; led the U.S. during the Civil War' },
  { n: 76, q: 'What did the Emancipation Proclamation do?', a: 'freed the slaves; freed slaves in the Confederacy/Confederate states/most Southern states' },
  { n: 77, q: 'What did Susan B. Anthony do?', a: 'fought for women\'s rights; fought for civil rights' },
  { n: 78, q: 'Name one war fought by the United States in the 1900s.', a: 'World War I; World War II; Korean War; Vietnam War; (Persian) Gulf War' },
  { n: 79, q: 'Who was President during World War I?', a: '(Woodrow) Wilson' },
  { n: 80, q: 'Who was President during the Great Depression and World War II?', a: '(Franklin) Roosevelt' },
  { n: 81, q: 'Who did the United States fight in World War II?', a: 'Japan, Germany, and Italy' },
  { n: 82, q: 'Before he was President, Eisenhower was a general. What war was he in?', a: 'World War II' },
  { n: 83, q: 'During the Cold War, what was the main concern of the United States?', a: 'Communism' },
  { n: 84, q: 'What movement tried to end racial discrimination?', a: 'the civil rights (movement)' },
  { n: 85, q: 'What did Martin Luther King, Jr. do?', a: 'fought for civil rights; worked for equality for all Americans' },
  { n: 86, q: 'What major event happened on September 11, 2001, in the United States?', a: 'Terrorists attacked the United States' },
  { n: 87, q: 'Name one American Indian tribe in the United States.', a: 'Cherokee, Navajo, Sioux, Chippewa, Choctaw, Pueblo, Apache, Iroquois, Creek, Blackfeet, Seminole, Cheyenne, Arawak, Shawnee, Mohegan, Huron, Oneida, Lakota, Crow, Teton, Hopi, Inuit' },
  { n: 88, q: 'Name one of the two longest rivers in the United States.', a: 'Missouri (River); Mississippi (River)' },
  { n: 89, q: 'What ocean is on the West Coast of the United States?', a: 'Pacific (Ocean)' },
  { n: 90, q: 'What ocean is on the East Coast of the United States?', a: 'Atlantic (Ocean)' },
  { n: 91, q: 'Name one U.S. territory.', a: 'Puerto Rico; U.S. Virgin Islands; American Samoa; Northern Mariana Islands; Guam' },
  { n: 92, q: 'Name one state that borders Canada.', a: 'Maine, New Hampshire, Vermont, New York, Pennsylvania, Ohio, Michigan, Minnesota, North Dakota, Montana, Idaho, Washington, Alaska' },
  { n: 93, q: 'Name one state that borders Mexico.', a: 'California, Arizona, New Mexico, Texas' },
  { n: 94, q: 'What is the capital of the United States?', a: 'Washington, D.C.' },
  { n: 95, q: 'Where is the Statue of Liberty?', a: 'New York (Harbor); Liberty Island; (also acceptable: New Jersey, near New York City, on the Hudson River)' },
  { n: 96, q: 'Why does the flag have 13 stripes?', a: 'because there were 13 original colonies; the stripes represent the original colonies' },
  { n: 97, q: 'Why does the flag have 50 stars?', a: 'because there is one star for each state; there are 50 states' },
  { n: 98, q: 'What is the name of the national anthem?', a: 'The Star-Spangled Banner' },
  { n: 99, q: 'When do we celebrate Independence Day?', a: 'July 4' },
  { n: 100, q: 'Name two national U.S. holidays.', a: "New Year's Day; Martin Luther King, Jr. Day; Presidents' Day; Memorial Day; Independence Day; Labor Day; Columbus Day; Veterans Day; Thanksgiving; Christmas" }
];

// 2020 test (also the version in effect for filings on/after Oct 20, 2025): 128 questions.
// The officer asks up to 20; the applicant must answer 12 correctly to pass.
const CIVICS_2020 = [
  { n: 1,  q: 'What is the form of government of the United States?', a: 'Republic; Constitution-based federal republic; Representative democracy' },
  { n: 2,  q: 'What is the supreme law of the land?', a: '(U.S.) Constitution' },
  { n: 3,  q: 'Name one thing the U.S. Constitution does.', a: 'Forms the government; defines powers of government; defines the parts of government; protects the rights of the people' },
  { n: 4,  q: 'The U.S. Constitution starts with the words "We the People." What does "We the People" mean?', a: 'Self-government; popular sovereignty; consent of the governed; people should govern themselves; (example of) social contract' },
  { n: 5,  q: 'How are changes made to the U.S. Constitution?', a: 'Amendments; the amendment process' },
  { n: 6,  q: 'What does the Bill of Rights protect?', a: '(the basic) rights of Americans / of people living in the United States' },
  { n: 7,  q: 'How many amendments does the U.S. Constitution have?', a: 'Twenty-seven (27)' },
  { n: 8,  q: 'Why is the Declaration of Independence important?', a: 'It says America is free from British control; it says all people are created equal; it identifies inherent rights; it identifies individual freedoms' },
  { n: 9,  q: 'What founding document said the American colonies were free from Britain?', a: 'Declaration of Independence' },
  { n: 10, q: 'Name two important ideas from the Declaration of Independence and the U.S. Constitution.', a: 'Equality; liberty; social contract; natural rights; limited government; self-government' },
  { n: 11, q: 'The words "Life, Liberty, and the pursuit of Happiness" are in what founding document?', a: 'Declaration of Independence' },
  { n: 12, q: 'What is the economic system of the United States?', a: 'Capitalism; free market economy' },
  { n: 13, q: 'What is the rule of law?', a: 'Everyone must follow the law; leaders/government must obey the law; no one is above the law' },
  { n: 14, q: 'Many documents influenced the U.S. Constitution. Name one.', a: 'Declaration of Independence; Articles of Confederation; Federalist Papers; Anti-Federalist Papers; Virginia Declaration of Rights; Fundamental Orders of Connecticut; Mayflower Compact; Iroquois Great Law of Peace' },
  { n: 15, q: 'There are three branches of government. Why?', a: 'So one part does not become too powerful; checks and balances; separation of powers' },
  { n: 16, q: 'Name the three branches of government.', a: 'Legislative, executive, and judicial; Congress, president, and the courts' },
  { n: 17, q: 'The President of the United States is in charge of which branch of government?', a: 'Executive branch' },
  { n: 18, q: 'What part of the federal government writes laws?', a: '(U.S.) Congress; (U.S. or national) legislature; legislative branch' },
  { n: 19, q: 'What are the two parts of the U.S. Congress?', a: 'Senate and House (of Representatives)' },
  { n: 20, q: 'Name one power of the U.S. Congress.', a: 'Writes laws; declares war; makes the federal budget' },
  { n: 21, q: 'How many U.S. senators are there?', a: 'One hundred (100)' },
  { n: 22, q: 'How long is a term for a U.S. senator?', a: 'Six (6) years' },
  { n: 23, q: "Who is one of your state's U.S. senators now?", a: STATE },
  { n: 24, q: 'How many voting members are in the House of Representatives?', a: 'Four hundred thirty-five (435)' },
  { n: 25, q: 'How long is a term for a member of the House of Representatives?', a: 'Two (2) years' },
  { n: 26, q: 'Why do U.S. representatives serve shorter terms than U.S. senators?', a: 'To more closely follow public opinion' },
  { n: 27, q: 'How many senators does each state have?', a: 'Two (2)' },
  { n: 28, q: 'Why does each state have two senators?', a: 'Equal representation (for small states); the Great Compromise (Connecticut Compromise)' },
  { n: 29, q: 'Name your U.S. representative.', a: STATE },
  { n: 30, q: 'What is the name of the Speaker of the House of Representatives now?', a: '__SPEAKER__' },
  { n: 31, q: 'Who does a U.S. senator represent?', a: 'Citizens of their state' },
  { n: 32, q: 'Who elects U.S. senators?', a: 'Citizens from their state' },
  { n: 33, q: 'Who does a member of the House of Representatives represent?', a: 'Citizens in their (congressional) district' },
  { n: 34, q: 'Who elects members of the House of Representatives?', a: 'Citizens from their (congressional) district' },
  { n: 35, q: 'Some states have more representatives than other states. Why?', a: "(Because of) the state's population; because some states have more people" },
  { n: 36, q: 'The President of the United States is elected for how many years?', a: 'Four (4) years' },
  { n: 37, q: 'The President of the United States can serve only two terms. Why?', a: '(Because of) the 22nd Amendment; to keep the president from becoming too powerful' },
  { n: 38, q: 'What is the name of the President of the United States now?', a: '__PRESIDENT__' },
  { n: 39, q: 'What is the name of the Vice President of the United States now?', a: '__VICE_PRESIDENT__' },
  { n: 40, q: 'If the president can no longer serve, who becomes president?', a: 'The Vice President (of the United States)' },
  { n: 41, q: 'Name one power of the president.', a: 'Signs bills into law; vetoes bills; enforces laws; Commander in Chief (of the military); chief diplomat' },
  { n: 42, q: 'Who is Commander in Chief of the U.S. military?', a: 'The President (of the United States)' },
  { n: 43, q: 'Who signs bills to become laws?', a: 'The President (of the United States)' },
  { n: 44, q: 'Who vetoes bills?', a: 'The President (of the United States)' },
  { n: 45, q: 'Who appoints federal judges?', a: 'The President (of the United States)' },
  { n: 46, q: 'The executive branch has many parts. Name one.', a: 'President; Cabinet; federal departments and agencies' },
  { n: 47, q: "What does the President's Cabinet do?", a: 'Advises the President (of the United States)' },
  { n: 48, q: 'What are two Cabinet-level positions?', a: 'Attorney General; Secretary of Agriculture, Commerce, Defense, Education, Energy, Health and Human Services, Homeland Security, Housing and Urban Development, Interior, Labor, State, Transportation, Treasury, Veterans Affairs; Vice President' },
  { n: 49, q: 'Why is the Electoral College important?', a: 'It decides who is elected president; it provides a compromise between the popular election of the president and congressional selection' },
  { n: 50, q: 'What is one part of the judicial branch?', a: 'Supreme Court; federal courts' },
  { n: 51, q: 'What does the judicial branch do?', a: 'Reviews laws; explains laws; resolves disputes about the law; decides if a law goes against the (U.S.) Constitution' },
  { n: 52, q: 'What is the highest court in the United States?', a: 'Supreme Court' },
  { n: 53, q: 'How many seats are on the Supreme Court?', a: 'Nine (9)' },
  { n: 54, q: 'How many Supreme Court justices are usually needed to decide a case?', a: 'Five (5)' },
  { n: 55, q: 'How long do Supreme Court justices serve?', a: '(For) life; lifetime appointment; (until) retirement' },
  { n: 56, q: 'Supreme Court justices serve for life. Why?', a: 'To be independent (of politics); to limit outside (political) influence' },
  { n: 57, q: 'Who is the Chief Justice of the United States now?', a: '__CHIEF_JUSTICE__' },
  { n: 58, q: 'Name one power that is only for the federal government.', a: 'Print paper money; mint coins; declare war; create an army; make treaties; set foreign policy' },
  { n: 59, q: 'Name one power that is only for the states.', a: 'Provide schooling and education; provide protection (police); provide safety (fire departments); give a driver\'s license; approve zoning and land use' },
  { n: 60, q: 'What is the purpose of the 10th Amendment?', a: '(It states that the) powers not given to the federal government belong to the states or to the people' },
  { n: 61, q: 'Who is the governor of your state now?', a: STATE },
  { n: 62, q: 'What is the capital of your state?', a: STATE },
  { n: 63, q: 'There are four amendments to the U.S. Constitution about who can vote. Describe one of them.', a: 'Citizens eighteen (18) and older can vote; you don\'t have to pay (a poll tax) to vote; any citizen can vote (women and men); a male citizen of any race can vote' },
  { n: 64, q: 'Who can vote in federal elections, run for federal office, and serve on a jury in the United States?', a: 'Citizens; citizens of the United States; U.S. citizens' },
  { n: 65, q: 'What are three rights of everyone living in the United States?', a: 'Freedom of expression; freedom of speech; freedom of assembly; freedom to petition the government; freedom of religion; the right to bear arms' },
  { n: 66, q: 'What do we show loyalty to when we say the Pledge of Allegiance?', a: 'The United States; the flag' },
  { n: 67, q: 'Name two promises that new citizens make in the Oath of Allegiance.', a: 'Give up loyalty to other countries; defend the (U.S.) Constitution; obey the laws of the United States; serve in the military (if needed); serve the nation (if needed); be loyal to the United States' },
  { n: 68, q: 'How can people become United States citizens?', a: 'Naturalize; derive citizenship; be born in the United States' },
  { n: 69, q: 'What are two examples of civic participation in the United States?', a: 'Vote; run for office; join a political party; help with a campaign; join a civic/community group; give an elected official your opinion; contact elected officials; support or oppose an issue or policy; write to a newspaper' },
  { n: 70, q: 'What is one way Americans can serve their country?', a: 'Vote; pay taxes; obey the law; serve in the military; run for office; work for local, state, or federal government' },
  { n: 71, q: 'Why is it important to pay federal taxes?', a: 'Required by law; all people pay to fund the federal government; required by the Constitution (16th Amendment); civic duty' },
  { n: 72, q: 'It is important for all men age 18 through 25 to register for the Selective Service. Name one reason why.', a: 'Required by law; civic duty; makes the draft fair, if needed' },
  { n: 73, q: 'The colonists came to America for many reasons. Name one.', a: 'Freedom; political liberty; religious freedom; economic opportunity; escape persecution' },
  { n: 74, q: 'Who lived in America before the Europeans arrived?', a: 'American Indians; Native Americans' },
  { n: 75, q: 'What group of people was taken and sold as slaves?', a: 'Africans; people from Africa' },
  { n: 76, q: 'What war did the Americans fight to win independence from Britain?', a: 'American Revolution; the (American) Revolutionary War; War for (American) Independence' },
  { n: 77, q: 'Name one reason why the Americans declared independence from Britain.', a: 'High taxes (taxation without representation); British soldiers stayed in their houses (boarding, quartering); they did not have self-government; Boston Massacre; Boston Tea Party; Stamp Act; Sugar Act; Townshend Acts; Intolerable (Coercive) Acts' },
  { n: 78, q: 'Who wrote the Declaration of Independence?', a: '(Thomas) Jefferson' },
  { n: 79, q: 'When was the Declaration of Independence adopted?', a: 'July 4, 1776' },
  { n: 80, q: 'The American Revolution had many important events. Name one.', a: '(Battle of) Bunker Hill; Declaration of Independence; Washington Crossing the Delaware (Battle of Trenton); (Battle of) Saratoga; Valley Forge; (Battle of) Yorktown' },
  { n: 81, q: 'There were 13 original states. Name five.', a: 'New Hampshire, Massachusetts, Rhode Island, Connecticut, New York, New Jersey, Pennsylvania, Delaware, Maryland, Virginia, North Carolina, South Carolina, Georgia' },
  { n: 82, q: 'What founding document was written in 1787?', a: '(U.S.) Constitution' },
  { n: 83, q: 'The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.', a: '(James) Madison; (Alexander) Hamilton; (John) Jay; Publius' },
  { n: 84, q: 'Why were the Federalist Papers important?', a: 'They helped people understand the Constitution; they supported passing the Constitution' },
  { n: 85, q: 'Benjamin Franklin is famous for many things. Name one.', a: 'Founded the first free public libraries; first Postmaster General; helped write the Declaration of Independence; inventor; U.S. diplomat' },
  { n: 86, q: 'George Washington is famous for many things. Name one.', a: '"Father of Our Country"; first president; General of the Continental Army; President of the Constitutional Convention' },
  { n: 87, q: 'Thomas Jefferson is famous for many things. Name one.', a: 'Writer of the Declaration of Independence; third president; doubled the size of the U.S. (Louisiana Purchase); first Secretary of State; founded the University of Virginia' },
  { n: 88, q: 'James Madison is famous for many things. Name one.', a: '"Father of the Constitution"; fourth president; president during the War of 1812; one of the writers of the Federalist Papers' },
  { n: 89, q: 'Alexander Hamilton is famous for many things. Name one.', a: 'First Secretary of the Treasury; one of the writers of the Federalist Papers; helped establish the First Bank of the U.S.; aide to General Washington; member of the Continental Congress' },
  { n: 90, q: 'What territory did the United States buy from France in 1803?', a: 'Louisiana Territory; Louisiana' },
  { n: 91, q: 'Name one war fought by the United States in the 1800s.', a: 'War of 1812; Mexican-American War; Civil War; Spanish-American War' },
  { n: 92, q: 'Name the U.S. war between the North and the South.', a: 'The Civil War' },
  { n: 93, q: 'The Civil War had many important events. Name one.', a: '(Battle of) Fort Sumter; Emancipation Proclamation; (Battle of) Vicksburg; (Battle of) Gettysburg; Sherman\'s March; (Surrender at) Appomattox; (Battle of) Antietam; Lincoln was assassinated' },
  { n: 94, q: 'Abraham Lincoln is famous for many things. Name one.', a: 'Freed the slaves (Emancipation Proclamation); saved/preserved the Union; led the U.S. during the Civil War; 16th president; delivered the Gettysburg Address' },
  { n: 95, q: 'What did the Emancipation Proclamation do?', a: 'Freed the slaves; freed slaves in the Confederacy/Confederate states/most Southern states' },
  { n: 96, q: 'What U.S. war ended slavery?', a: 'The Civil War' },
  { n: 97, q: 'What amendment gives citizenship to all persons born in the United States?', a: '14th Amendment' },
  { n: 98, q: 'When did all men get the right to vote?', a: 'After the Civil War; during Reconstruction; (with the) 15th Amendment; 1870' },
  { n: 99, q: "Name one leader of the women's rights movement in the 1800s.", a: 'Susan B. Anthony; Elizabeth Cady Stanton; Sojourner Truth; Harriet Tubman; Lucretia Mott; Lucy Stone' },
  { n: 100, q: 'Name one war fought by the United States in the 1900s.', a: 'World War I; World War II; Korean War; Vietnam War; (Persian) Gulf War' },
  { n: 101, q: 'Why did the United States enter World War I?', a: 'Because Germany attacked U.S. (civilian) ships; to support the Allied Powers; to oppose the Central Powers' },
  { n: 102, q: 'When did all women get the right to vote?', a: '1920; after World War I; (with the) 19th Amendment' },
  { n: 103, q: 'What was the Great Depression?', a: 'Longest economic recession in modern history' },
  { n: 104, q: 'When did the Great Depression start?', a: 'The Great Crash (1929); stock market crash of 1929' },
  { n: 105, q: 'Who was president during the Great Depression and World War II?', a: '(Franklin) Roosevelt' },
  { n: 106, q: 'Why did the United States enter World War II?', a: '(Bombing of) Pearl Harbor; Japanese attacked Pearl Harbor; to support the Allied Powers; to oppose the Axis Powers' },
  { n: 107, q: 'Dwight Eisenhower is famous for many things. Name one.', a: 'General during World War II; president during the Korean War; 34th president; signed the Federal-Aid Highway Act of 1956 (created the Interstate System)' },
  { n: 108, q: "Who was the United States' main rival during the Cold War?", a: 'Soviet Union; USSR; Russia' },
  { n: 109, q: 'During the Cold War, what was one main concern of the United States?', a: 'Communism; nuclear war' },
  { n: 110, q: 'Why did the United States enter the Korean War?', a: 'To stop the spread of communism' },
  { n: 111, q: 'Why did the United States enter the Vietnam War?', a: 'To stop the spread of communism' },
  { n: 112, q: 'What did the civil rights movement do?', a: 'Fought to end racial discrimination' },
  { n: 113, q: 'Martin Luther King, Jr. is famous for many things. Name one.', a: 'Fought for civil rights; worked for equality for all Americans' },
  { n: 114, q: 'Why did the United States enter the Persian Gulf War?', a: 'To force the Iraqi military from Kuwait' },
  { n: 115, q: 'What major event happened on September 11, 2001 in the United States?', a: 'Terrorists attacked the United States (crashed planes into the World Trade Center and the Pentagon, and one in a field in Pennsylvania)' },
  { n: 116, q: 'Name one U.S. military conflict after the September 11, 2001 attacks.', a: '(Global) War on Terror; War in Afghanistan; War in Iraq' },
  { n: 117, q: 'Name one American Indian tribe in the United States.', a: 'Apache, Blackfeet, Cayuga, Cherokee, Cheyenne, Chippewa, Choctaw, Creek, Crow, Hopi, Huron, Inupiat, Lakota, Mohawk, Mohegan, Navajo, Oneida, Onondaga, Pueblo, Seminole, Seneca, Shawnee, Sioux, Teton, Tuscarora' },
  { n: 118, q: 'Name one example of an American innovation.', a: 'Light bulb; automobile; skyscrapers; airplane; assembly line; landing on the moon; integrated circuit (IC)' },
  { n: 119, q: 'What is the capital of the United States?', a: 'Washington, D.C.' },
  { n: 120, q: 'Where is the Statue of Liberty?', a: 'New York (Harbor); Liberty Island; (also acceptable: New Jersey, near New York City, on the Hudson River)' },
  { n: 121, q: 'Why does the flag have 13 stripes?', a: '(Because there were) 13 original colonies; the stripes represent the original colonies' },
  { n: 122, q: 'Why does the flag have 50 stars?', a: 'One star for each state; each star represents a state; there are 50 states' },
  { n: 123, q: 'What is the name of the national anthem?', a: 'The Star-Spangled Banner' },
  { n: 124, q: 'The Nation\'s first motto was "E Pluribus Unum." What does that mean?', a: 'Out of many, one; we all become one' },
  { n: 125, q: 'What is Independence Day?', a: 'A holiday to celebrate U.S. independence (from Britain); the country\'s birthday' },
  { n: 126, q: 'Name three national U.S. holidays.', a: "New Year's Day; Martin Luther King, Jr. Day; Presidents Day (Washington's Birthday); Memorial Day; Independence Day; Labor Day; Columbus Day; Veterans Day; Thanksgiving Day; Christmas Day" },
  { n: 127, q: 'What is Memorial Day?', a: 'A holiday to honor soldiers who died in military service' },
  { n: 128, q: 'What is Veterans Day?', a: 'A holiday to honor people in the (U.S.) military; a holiday to honor people who have served' }
];

// Resolve the dynamic placeholders using the current officials.
function resolveBank(bank) {
  const map = {
    '__PRESIDENT__': CURRENT_OFFICIALS.president,
    '__VICE_PRESIDENT__': CURRENT_OFFICIALS.vicePresident,
    '__PRESIDENT_PARTY__': CURRENT_OFFICIALS.presidentParty,
    '__SPEAKER__': CURRENT_OFFICIALS.speaker,
    '__CHIEF_JUSTICE__': CURRENT_OFFICIALS.chiefJustice
  };
  return bank.map(item => ({ n: item.n, q: item.q, a: map[item.a] || item.a }));
}

module.exports = {
  CURRENT_OFFICIALS,
  CIVICS_2008: resolveBank(CIVICS_2008),
  CIVICS_2020: resolveBank(CIVICS_2020)
};
